import os
import math
from PIL import Image

BRAIN_DIR = '/Users/lap60488/.gemini/antigravity/brain/5faef06b-635b-4e2b-9213-c45ede334aef'
OUT_DIR = '/Users/lap60488/Downloads/game aaa/assets/sprites'

SPRITES = [
  ('chroma_tanjiro_kick_', 'tanjiro_kick.png', 'magenta'),
  ('chroma_tanjiro_jump_kick_', 'tanjiro_jump_kick.png', 'magenta'),
  ('chroma_tanjiro_crouch_kick_', 'tanjiro_crouch_kick.png', 'magenta'),
  ('chroma_nezuko_kick_', 'nezuko_kick.png', 'cyan'),
  ('chroma_nezuko_jump_kick_', 'nezuko_jump_kick.png', 'cyan'),
  ('chroma_nezuko_crouch_kick_', 'nezuko_crouch_kick.png', 'cyan'),
  ('chroma_zenitsu_kick_', 'zenitsu_kick.png', 'blue'),
  ('chroma_zenitsu_jump_kick_', 'zenitsu_jump_kick.png', 'blue'),
  ('chroma_zenitsu_crouch_kick_', 'zenitsu_crouch_kick.png', 'blue'),
  ('chroma_inosuke_kick_', 'inosuke_kick.png', 'magenta'),
  ('chroma_inosuke_jump_kick_', 'inosuke_jump_kick.png', 'magenta'),
  ('chroma_inosuke_crouch_kick_', 'inosuke_crouch_kick.png', 'magenta'),
]

def kill_pink(prefix, dest_file, ctype):
    files = os.listdir(BRAIN_DIR)
    actual_file = next((f for f in files if f.startswith(prefix) and f.endswith('.png')), None)
    if not actual_file:
        print(f"  ✗ Not found: {prefix}")
        return
        
    src_path = os.path.join(BRAIN_DIR, actual_file)
    dest_path = os.path.join(OUT_DIR, dest_file)
    
    img = Image.open(src_path).convert("RGBA")
    pixels = img.load()
    width, height = img.size
    
    for y in range(height):
        for x in range(width):
            r, g, b, a = pixels[x, y]
            
            # Step 1: Neutralize ALL background-colored artifacts everywhere based purely on Channel dominance!
            is_fringe_or_background = False
            
            if ctype == 'magenta':
                # Deep magenta fringe implies R and B are dominant over G. And if it's the black lineart, G is very low.
                # If Green is lower than 100, we are safe to assume it's NOT skin (Skin has G > 150).
                # Wait, Inosuke's blue pants might have G < 100. (e.g. R=30, G=40, B=100).
                # But Inosuke's pants have High B, Low R! Magenta has High R and High B.
                # So if BOTH R and B are greater than G by a large margin (say > 40), it's Magenta!
                # OR if it's just really dark (R<60, G<60, B<60).
                if g < 90 and r > g + 30 and b > g + 30: 
                    is_fringe_or_background = True
                    
            elif ctype == 'cyan':
                # Cyan implies G and B are dominant, and R is very low.
                if r < 90 and g > r + 30 and b > r + 30:
                    is_fringe_or_background = True
                    
            elif ctype == 'blue':
                opp = max(r, g)
                if opp < 90 and b > opp + 40:
                    is_fringe_or_background = True

            # Step 2: Also deal with the Pure Bright glow (Gradients generated by AI near lineart edges that might be dist > 120)
            if ctype == 'magenta':
                if (r > 100 and b > 100 and g < 120): is_fringe_or_background = True
            elif ctype == 'cyan':
                if (g > 100 and b > 100 and r < 120): is_fringe_or_background = True
            elif ctype == 'blue':
                if (b > 120 and r < 100 and g < 100): is_fringe_or_background = True


            if is_fringe_or_background:
                # Murder the color. Make it pure black.
                pixels[x, y] = (0, 0, 0, a)  # we keep the alpha it currently has! Since my previous pass faded the alpha.
                # Wait, if I am loading the ORIGINAL image from BRAIN_DIR, alpha is 255!
                # I should not load from BRAIN_DIR, I should load from OUT_DIR to modify the ALREADY PROCESSED image!
                pass

def kill_pink_post_process(dest_file, ctype):
    dest_path = os.path.join(OUT_DIR, dest_file)
    if not os.path.exists(dest_path):
        print(f"Skipping {dest_file}")
        return
        
    img = Image.open(dest_path).convert("RGBA")
    pixels = img.load()
    width, height = img.size
    
    fixes = 0
    for y in range(height):
        for x in range(width):
            r, g, b, a = pixels[x, y]
            if a == 0: continue
            
            is_fringe = False
            
            # The issue is that there's a glowing pink outline.
            # Pink/Magenta is High R, High B, Low G.
            # Just target ANYTHING with strong Magenta, Cyan, or Blue dominance and nuke it to black.
            if ctype == 'magenta':
                if r > g + 10 and b > g + 10 and g < 100: is_fringe = True
            elif ctype == 'cyan':
                if g > r + 10 and b > r + 10 and r < 100: is_fringe = True
            elif ctype == 'blue':
                if b > r + 30 and b > g + 30 and r < 100 and g < 100: is_fringe = True

            # If pixel is heavily tinted and is near transparent pixels (it is an edge), 
            # Or if it's just visually undeniably fluorescent.
            if is_fringe:
                # Force to black
                pixels[x, y] = (0, 0, 0, a)
                fixes += 1
                
    img.save(dest_path)
    print(f"  ✓ Fixed {dest_file}: {fixes} edge pixels blackened.")

print("KILL PINK SCRIPT RUNNING POST-PROCESSING...")
for _, dest, ctype in SPRITES:
    kill_pink_post_process(dest, ctype)
print("Complete.")
